### ISSUE TITLE
Add SPDY support

### ISSUE THREAD

**Issue by PaintNinja** [frustra/mods.io#13]
Please add SPDY v3 support to your mods.io webserver if possible. Thanks! :)

By serving your webpages using the SPDY protocol, page load times would be significantly faster and overall less bandwidth would be used for the same content.

Current status: http://spdycheck.org/#mods.io
Benchmarks: http://www.favbrowser.com/spdy-vs-http-benchmarks/

**Comment by xthexder** [comment]
SPDY 3.1 has been enabled on nginx, thanks for letting us know.
